name: CI

on: [push]

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: sactions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, World!
    - name: Run a multi-line script
      run: 
        echo Add other actions to the build job
        secho This can be unit tests, etc.
